# Generated by Django 2.1 on 2019-12-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('1', 'ADMIN'), ('2', 'FINANCE_ADMIN'), ('3', 'SALES_ADMIN'), ('4', 'HR_ADMIN'), ('5', 'ENGG_ADMIN'), ('0', 'N/A')], default='0', max_length=1)),
            ],
        ),
    ]
